# Generated by Django 5.0.2 on 2024-02-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fees',
            field=models.IntegerField(),
        ),
    ]
